In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data_df = pd.read_csv("./pricedelta.csv")
data_df

Dates      aapl       amzn      msft       goog  \
0    2016-01-05T00:00:00.000000000 -2.550804  -3.200012  0.239204   0.739990   
1    2016-01-06T00:00:00.000000000 -1.942085  -1.139954 -0.956821   1.039978   
2    2016-01-07T00:00:00.000000000 -4.106422 -24.710022 -1.798817 -17.229980   
3    2016-01-08T00:00:00.000000000  0.492782  -0.890014  0.153099 -11.920044   
4    2016-01-11T00:00:00.000000000  1.516953  10.690002 -0.028709   1.560058   
..                             ...       ...        ...       ...        ...   
427  2017-09-14T00:00:00.000000000 -1.369995  -7.389954 -0.440002  -9.980042   
428  2017-09-15T00:00:00.000000000  1.600006  -5.420044  0.540001  -4.820007   
429  2017-09-18T00:00:00.000000000 -1.210007 -12.599976 -0.149994  -5.289978   
430  2017-09-19T00:00:00.000000000  0.059998  -4.330017  0.279998   6.809998   
431  2017-09-20T00:00:00.000000000 -2.659989   3.350037 -0.500000   9.770019   

          xom       apc       cvx         c        gs       jpm       aet  \
0    0.619774 -0.605922  0.706352 -0.264831 -2.975281  0.105781  1.492623   
1   -0.610390 -4.718247 -3.290100 -0.725819 -4.145889 -0.884708 -0.549904   
2   -1.164451 -3.635540 -2.834702 -2.510910 -5.092087 -2.442589  0.049087   
3   -1.446183  0.446995 -0.827179 -1.402592 -0.663376 -1.298229 -3.142364   
4   -0.939079 -2.791214 -1.263992  0.706192  1.746155 -0.086552 -1.718475   
..        ...       ...       ...       ...       ...       ...       ...   
427  0.319999  0.399998  0.269997 -0.150001  0.290008 -0.180001  0.479996   
428 -0.019996  0.020000  0.180000 -0.199997 -1.630005  0.650002 -0.100006   
429  0.019996  0.209999  0.560005  1.559997  2.309998  1.299995 -1.679993   
430  0.130005  0.000000  1.149994  0.550004  1.380005  1.020004 -4.960007   
431  0.330002  1.050003  0.030007  0.309997  0.879989  0.659996 -1.009994   

          jnj       dgx       spy       xlf       sso       sds   uso  
0    0.400551  0.019310  0.328171  0.054300  0.267940 -0.239998 -0.32  
1   -0.486397 -1.062820 -2.451645 -0.217214 -1.637440  2.079994 -0.55  
2   -1.115806 -1.478310 -4.604080 -0.392194 -2.828319  4.040001 -0.21  
3   -1.010910 -0.340065 -2.055924 -0.211180 -1.210716  1.959999 -0.10  
4   -0.562683  0.505249  0.183396  0.018101  0.029773 -0.159996 -0.55  
..        ...       ...       ...       ...       ...       ...   ...  
427  1.729996 -1.290001 -0.079605 -0.049793 -0.070000  0.040001  0.06  
428  0.270004 -0.639999  0.335006  0.073001  0.280007 -0.130002  0.07  
429  0.930008 -1.099998  0.529999  0.289999  0.369995 -0.159999 -0.03  
430 -0.160004 -2.000000  0.250000  0.190001  0.139999 -0.090001 -0.06  
431 -2.000000 -0.059998  0.089997  0.150000  0.080002 -0.039997  0.13  

[432 rows x 19 columns]

In [16]:
data_df["amzn_ber"] = data_df["amzn"].apply(lambda x: 1 if x > 0 else 0)
data_df["jpm_ber"] = data_df["jpm"].apply(lambda x: 1 if x > 0 else 0)
data_df["spy_ber"] = data_df["spy"].apply(lambda x: 1 if x > 0 else 0)

In [36]:
# Joint pmf of amzn, jpm, spy
joint_pmf_matrix = np.zeros((2,2,2))
for i in range(2):
    for j in range(2):
        for k in range(2):
            joint_pmf_matrix[i,j,k] = len(data_df.query(f"amzn_ber == {i} and jpm_ber == {j} and spy_ber == {k}")) / len(data_df)
joint_pmf_matrix

array([[[0.22453704, 0.03472222],
        [0.07407407, 0.1087963 ]],

       [[0.11574074, 0.10416667],
        [0.03703704, 0.30092593]]])

In [41]:
# Marginal pmf
# 1. (amzn, jpm) over spy
amzn_jpm_marginal = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        amzn_jpm_marginal[i,j] = len(data_df.query(f"amzn_ber == {i} and jpm_ber == {j}")) / len(data_df)


# 2. (amzn, spy) over jpm
amzn_spy_marginal = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        amzn_spy_marginal[i,j] = len(data_df.query(f"amzn_ber == {i} and spy_ber == {j}")) / len(data_df)


# 3. (jpm, spy) over amzn
jpm_spy_marginal = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        jpm_spy_marginal[i,j] = len(data_df.query(f"jpm_ber == {i} and spy_ber == {j}")) / len(data_df)

In [42]:
amzn_jpm_marginal

array([[0.25925926, 0.18287037],
       [0.21990741, 0.33796296]])

In [43]:
amzn_spy_marginal

array([[0.29861111, 0.14351852],
       [0.15277778, 0.40509259]])

In [44]:
jpm_spy_marginal

array([[0.34027778, 0.13888889],
       [0.11111111, 0.40972222]])

In [53]:
# Conditional pmf
# 1. (amzn, jpm) given spy
amzn_jpm_coniditional = np.zeros((2,2,2))
for i in range(2):
    for j in range(2):
        for k in range(2):
            amzn_jpm_coniditional[i,j,k] = len(data_df.query(f"amzn_ber == {i} and jpm_ber == {j} and spy_ber == {k}")) / len(data_df.query(f"spy_ber == {k}"))


# 2. (amzn, spy) given jpm
amzn_spy_coniditional = np.zeros((2,2,2))
for i in range(2):
    for j in range(2):
        for k in range(2):
            amzn_spy_coniditional[i,j,k] = len(data_df.query(f"amzn_ber == {i} and spy_ber == {j} and jpm_ber == {k}")) / len(data_df.query(f"jpm_ber == {k}"))


# 3. (jpm, spy) given amzn
jpm_spy_coniditional = np.zeros((2,2,2))
for i in range(2):
    for j in range(2):
        for k in range(2):
            jpm_spy_coniditional[i,j,k] = len(data_df.query(f"jpm_ber == {i} and spy_ber == {j} and amzn_ber == {k}")) / len(data_df.query(f"amzn_ber == {k}"))

In [54]:
amzn_jpm_coniditional

array([[[0.4974359 , 0.06329114],
        [0.16410256, 0.19831224]],

       [[0.25641026, 0.18987342],
        [0.08205128, 0.54852321]]])

In [55]:
amzn_spy_coniditional

array([[[0.46859903, 0.14222222],
        [0.07246377, 0.20888889]],

       [[0.24154589, 0.07111111],
        [0.2173913 , 0.57777778]]])

In [56]:
jpm_spy_coniditional

array([[[0.5078534 , 0.20746888],
        [0.07853403, 0.18672199]],

       [[0.16753927, 0.06639004],
        [0.2460733 , 0.53941909]]])